# Generated by Django 5.2.5 on 2025-09-06 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('case_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('category', models.CharField(max_length=100)),
                ('scenario', models.TextField(blank=True)),
                ('instructions_for_patient', models.TextField(blank=True)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('age', models.CharField(blank=True, max_length=20)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('instruction_for_doc', models.TextField(blank=True)),
                ('case_type', models.CharField(blank=True, max_length=100)),
                ('examination_details', models.TextField(blank=True)),
                ('info_for_facilitator_exam_findings', models.TextField(blank=True)),
                ('specific_questions', models.TextField(blank=True)),
                ('management_plan', models.TextField(blank=True)),
                ('case_commentary', models.TextField(blank=True)),
                ('pitfalls', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('current_turn', models.IntegerField(default=0)),
                ('patient_paused', models.BooleanField(default=False)),
                ('transcript', models.TextField(blank=True)),
                ('conversation_history', models.JSONField(default=list)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulation.case')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.FloatField()),
                ('pass_fail', models.BooleanField()),
                ('what_went_well', models.TextField()),
                ('areas_for_improvement', models.TextField()),
                ('specific_recommendations', models.TextField()),
                ('key_points_covered', models.JSONField(default=list)),
                ('key_points_missed', models.JSONField(default=list)),
                ('compliance_analysis', models.JSONField(default=dict)),
                ('rag_sources', models.JSONField(default=list)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generation_time_seconds', models.FloatField(blank=True, null=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='simulation.session')),
            ],
        ),
        migrations.CreateModel(
            name='AIAgentState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_persona', models.TextField(blank=True)),
                ('patient_memory', models.JSONField(default=list)),
                ('patient_context', models.JSONField(default=dict)),
                ('last_examiner_request', models.TextField(blank=True)),
                ('examiner_findings_retrieved', models.BooleanField(default=False)),
                ('feedback_generated', models.BooleanField(default=False)),
                ('rag_queries_used', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='simulation.session')),
            ],
        ),
    ]
